hide_download: true
hide_download_original: null
leftnav:
- identifier: d2c84a9c-f74b-99a3-955b-77b6a38594ec
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 8ee97cde-34c9-0032-f5b6-19eb69b2b7c2
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 72a3069a-2187-aa33-e550-524552414921
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: b181625f-50d4-197a-53da-78640d3431e7
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
